### ISSUE TITLE
PPPoE Configurator for Dummies? Alternatively PPPoE Internet Support?

### ISSUE THREAD

**Issue by RaTcHeT302** [solus-project/linux-driver-management#9]
Can a PPPoE configurator be added? I can't connect to my broadbad internet on Solus, and I'm stuck on Lubuntu as I have no internet at all on Solus. The DSL setting doesn't do anything on Solus, it just fails to connect. It works fine on Lubuntu.

I can't compile RP-PPPoE, and unless PPPoE is included by default, many users will most likely have to skip Solus and move on to another Linux distribution. I want to give Solus a shot, but as long as I'm unable to even connect to the internet, the whole system is mostly unusable.

**Comment by ikeydoherty** [comment]
I'm not entirely convinced this is something LDM needs to handle, we just need to improve PPPoE support in Network Manager, no?

**Comment by RaTcHeT302** [comment]
It's not about LDM, I just have no clue where to make this issue. The whole project is too spread out and I can't even tell where the main Solus repository is supposed to be. Can it be renamed to Solus-Main or Solus-OS-Main or something more verbose?

**Comment by W-Floyd** [comment]
@RaTcHeT302 that would be https://dev.solus-project.com/

**Comment by RaTcHeT302** [comment]
Does this look correct, or should I delete it?
https://dev.solus-project.com/T5647

**Comment by RaTcHeT302** [comment]
I guess I can't delete that now, I hope it's correct at least.

**Comment by ikeydoherty** [comment]
Solus-Main? Solus-OS-Main? We're called Solus, and our own homepage links directly to the tracker (and not GitHub). Nobody told you that we were on GitHub its something you have assumed, and isn't an indication that we're "too spread out" :)

Thus, I'm not renaming anything, `/solus-project` is the GitHub organisation that houses code projects with collaboration from outside teams. Our dev portal handles OS issues and packaging.

**Comment by RaTcHeT302** [comment]
I didn't assume anything, there's a GitHub link on this page.
https://solus-project.com/support/

The very first link is linux-driver-management and solus-sc, to me they are not self explanatory at all.
https://github.com/solus-project

I don't understand why you have to be so mean about it, I'm just telling you that I had difficulty finding where the main project actually is, and I still have no idea where it actually is. I don't know how your project works, or how you set it up, you can't expect me to know everything in the first five minutes. 

It's up to you to make the user experience as easy, intuitive and accessible as possible.

At the end of the day I'm just trying to help out by reporting an issue which other users might've been too embarassed to post about for these reasons. Maybe they also struggled to find the project's main repository, so they gave up and moved to another OS instead.
